version: '3.8'
services:

  techbuzz-db:
    image: postgres:15.1-alpine
    container_name: techbuzz-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
