name: Build

env:
  APP_NAME: techbuzz
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/techbuzz

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '19']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }} (${{ matrix.distribution }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ env.DOCKER_IMAGE_NAME }}
          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}
